BHnew-masterrr/BikeHireSystem-master/BikeApp/Models/UsersAndBike.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAndBike
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string BikeModel { get; set; }
        public Nullable<int> BikeId { get; set; }
        public Nullable<System.DateTime> StardDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}

BHnew-masterrr/BikeHireSystem-master/BikeApp/Models/UsersAndBikes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

BHnew-masterrr/BikeHireSystem-master/BikeApp/Controllers/UsersAndBikesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BikeApp.Models;

namespace BikeApp.Controllers
{
    public class UsersAndBikesController : Controller
    {
        private BikeHireDatabaseEntities3 db = new BikeHireDatabaseEntities3();

        // GET: UsersAndBikes
        public ActionResult Index(string searchString)
        {
            
            var Bikes = from m in db.UsersAndBikes
                        select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                Bikes = Bikes.Where(j => j.BikeModel.Contains(searchString) || j.Name.Contains(searchString));
                return View(Bikes.ToList());
            }

            else { return View(db.UsersAndBikes.ToList()); }
        }

        // GET: UsersAndBikes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersAndBike usersAndBike = db.UsersAndBikes.Find(id);
            if (usersAndBike == null)
            {
                return HttpNotFound();
            }
            return View(usersAndBike);
        }

        // GET: UsersAndBikes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersAndBikes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,BikeModel,BikeId,StardDate,EndDate")] UsersAndBike usersAndBike)
        {
            if (ModelState.IsValid)
            {
                db.UsersAndBikes.Add(usersAndBike);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usersAndBike);
        }

        // GET: UsersAndBikes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersAndBike usersAndBike = db.UsersAndBikes.Find(id);
            if (usersAndBike == null)
            {
                return HttpNotFound();
            }
            return View(usersAndBike);
        }

        // POST: UsersAndBikes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,BikeModel,BikeId,StardDate,EndDate")] UsersAndBike usersAndBike)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usersAndBike).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usersAndBike);
        }

        // GET: UsersAndBikes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsersAndBike usersAndBike = db.UsersAndBikes.Find(id);
            if (usersAndBike == null)
            {
                return HttpNotFound();
            }
            return View(usersAndBike);
        }

        // POST: UsersAndBikes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UsersAndBike usersAndBike = db.UsersAndBikes.Find(id);
            db.UsersAndBikes.Remove(usersAndBike);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult filterUser(string searchString)
        {

            var users = from m in db.UsersAndBikes
                        select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(w => w.Name.Contains(searchString));
            }

            return View(users.ToList());
        }

        public ActionResult filterBike(string searchString)
        {

            var bikes = from m in db.UsersAndBikes
                        select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                bikes = bikes.Where(g => g.BikeModel.Contains(searchString));
            }

            return View(bikes.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BHnew-masterrr/BikeHireSystem-master/BikeApp/Views/UsersAndBikes/Create.cshtml
@model BikeApp.Models.UsersAndBike

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UsersAndBike</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StardDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StardDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StardDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BHnew-masterrr/BikeHireSystem-master/BikeApp/Views/UsersAndBikes/Delete.cshtml
@model BikeApp.Models.UsersAndBike

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UsersAndBike</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StardDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StardDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BHnew-masterrr/BikeHireSystem-master/BikeApp/Views/UsersAndBikes/Details.cshtml
@model BikeApp.Models.UsersAndBike

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UsersAndBike</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeModel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeModel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BikeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BikeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StardDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StardDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BHnew-masterrr/BikeHireSystem-master/BikeApp/Views/UsersAndBikes/Edit.cshtml
@model BikeApp.Models.UsersAndBike

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UsersAndBike</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BikeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BikeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BikeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StardDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StardDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StardDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BHnew-masterrr/BikeHireSystem-master/BikeApp/Views/UsersAndBikes/Index.cshtml
@model IEnumerable<BikeApp.Models.UsersAndBike>

@{
    ViewBag.Title = "Index";
}

<h2>Users and Bikes information Page:</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<form asp-controller="UsersAndBikes" asp-action="filterUser">
    <p>
        User Name: <input type="text" name="SearchString">
        <input type="submit" value="Search" />
    </p>
</form>
<form asp-controller="UsersAndBikes" asp-action="filterBike">
    <p>
        Bike Model: <input type="text" name="SearchString">
        <input type="submit" value="Search" />
    </p>
</form>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeModel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BikeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StardDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BikeModel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BikeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StardDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>